/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2020-02-06 23:26:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>H+ Sport</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<header id=\"home\" class=\"header\">\r\n");
      out.write("\t\t<nav class=\"nav\" role=\"navigation\">\r\n");
      out.write("\t\t\t<div class=\"container nav-elements\">\r\n");
      out.write("\t\t\t\t<div class=\"branding\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#home\"><img src=\"images/hpluslogo.svg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Logo - H Plus Sports\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- branding -->\r\n");
      out.write("\t\t\t\t<ul class=\"navbar\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"home\">home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"orderHistory\">order history</a></li>\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"viewProfile\">view my profile</a></li> -->\r\n");
      out.write("\t\t\t\t\t<li><a href='");
      out.print(response.encodeURL("viewProfile"));
      out.write("'>view\r\n");
      out.write("\t\t\t\t\t\t\tmy profile</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href='logout'>logout</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"redirect\">linkedIn</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<!-- navbar -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- container nav-elements -->\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<!-- <div class=\"container tagline\">\r\n");
      out.write("    <h1 class=\"headline\">Our Mission</h1>\r\n");
      out.write("    <p>We support and encourage <em>active and healthy</em> lifestyles, by offering <em>ethically sourced</em> and <em>eco-friendly</em> nutritional products for the <em>performance-driven</em> athlete.</p>\r\n");
      out.write("  </div>container tagline -->\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write(" \t");
      com.test.beans.User user = null;
      user = (com.test.beans.User) _jspx_page_context.getAttribute("user", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (user == null){
        throw new java.lang.InstantiationException("bean user not found within scope");
      }
      out.write("  \r\n");
      out.write("\t<section>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section id=\"profile\" class=\"section\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h2 class=\"headline\"></h2>\r\n");
      out.write("\t\t\t<table id=\"profile\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Username</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.test.beans.User)_jspx_page_context.findAttribute("user")).getUsername())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>First Name</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.test.beans.User)_jspx_page_context.findAttribute("user")).getFirstName())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Last Name</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.test.beans.User)_jspx_page_context.findAttribute("user")).getLastName())));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Age</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.age}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Interested in</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.activity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<nav class=\"nav\" role=\"navigation\">\r\n");
      out.write("\t\t\t\t<div class=\"container nav-elements\">\r\n");
      out.write("\t\t\t\t\t<div class=\"branding\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#home\"><img src=\"images/hpluslogo.svg\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"Logo - H Plus Sports\"></a>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"address\">\r\n");
      out.write("\t\t\t\t\t\t\t100 Main Street<br> Seattle, WA 98144\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<p class=\"legal\">H+ Sport is a fictitious brand created for project experiment. All products and\r\n");
      out.write("\t\t\t\tpeople associated with H+ Sport are also fictitious. Any resemblance\r\n");
      out.write("\t\t\t\tto real brands, products, or people is purely coincidental.\r\n");
      out.write("\t\t\t\tInformation provided about the product is also fictitious and should\r\n");
      out.write("\t\t\t\tnot be construed to be representative of actual products on the\r\n");
      out.write("\t\t\t\tmarket in a similar product category.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- container -->\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
