/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2020-02-06 06:12:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import java.util.ArrayList;
import com.test.beans.Product;
import java.util.List;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>H+ Sport</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<header id=\"home\" class=\"header\">\n");
      out.write("\t\t<nav class=\"nav\" role=\"navigation\">\n");
      out.write("\t\t\t<div class=\"container nav-elements\">\n");
      out.write("\t\t\t\t<div class=\"branding\">\n");
      out.write("\t\t\t\t\t<a href=\"home\"><img src=\"images/hpluslogo.svg\"\n");
      out.write("\t\t\t\t\t\talt=\"Logo - H Plus Sports\"></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- branding -->\n");
      out.write("\t\t\t\t<ul class=\"navbar\">\n");
      out.write("\t\t\t\t\t<li><a href=\"home\">home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#products\">products</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#history\">history</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"login\">login</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#people\">people</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#search\">search</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"register\">new user?</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"redirect\">linkedIn</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<!-- navbar -->\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- navbar -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- container nav-elements -->\n");
      out.write("\t\t</nav>\n");
      out.write("\t</header>\n");
      out.write("\n");
      out.write("\t<section id=\"products\" class=\"section\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<h2 class=\"headline\">Products</h2>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\tH+ Sport is <em>dedicated to creating</em> eco-friendly,\n");
      out.write("\t\t\t\thigh-quality, nutrient-rich, nutritional products that <em>enhance\n");
      out.write("\t\t\t\t\tactive lifestyles</em>.\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t");

				if (session.getAttribute("noofproducts") != null) {
			
      out.write("\n");
      out.write("\t\t\t<span id=\"size\"\n");
      out.write("\t\t\t\ttitle=\"");
      out.print((ArrayList) session.getAttribute("noofproducts"));
      out.write("\">Items\n");
      out.write("\t\t\t\tin Cart: ");
      out.print(((ArrayList) session.getAttribute("noofproducts")).size());
      out.write("</span>\n");
      out.write("\t\t\t");

				} else {
			
      out.write("\n");
      out.write("\t\t\t<span id=\"size\">Items in Cart: 0</span>\n");
      out.write("\t\t\t");

				}
			
      out.write("\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t");
      out.write('\n');
      out.write('	');
      out.write('	');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<div class=\"productContainer\">\n");
      out.write("\n");
      out.write("\t\t\t");

				List<Product> products = (ArrayList) request.getAttribute("products");
				Iterator<Product> iterator = products.iterator();
				while (iterator.hasNext()) {
					Product product = iterator.next();
			
      out.write("\n");
      out.write("\t\t\t<form method=\"get\" action=\"addProducts\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"productContainerItem\">\n");
      out.write("\t\t\t\t\t<img id=\"pic3\" src=\"");
      out.print(product.getProductImgPath());
      out.write("\"> <input\n");
      out.write("\t\t\t\t\t\ttype=\"text\" name=\"product\" value=\"");
      out.print(product.getProductName());
      out.write("\"><br />\n");
      out.write("\t\t\t\t\t<button>Add to Cart</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t");

				}
			
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<!-- #products -->\n");
      out.write("\n");
      out.write("\t<section id=\"search\" class=\"section\">\n");
      out.write("\t\t<header class=\"imageheader\"></header>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<h2 class=\"headline\">Search Products</h2>\n");
      out.write("\t\t\t<form action=\"search\" method=\"get\">\n");
      out.write("\t\t\t\t<label class=\"card-title\">Search your product</label> <input\n");
      out.write("\t\t\t\t\ttype=\"search\" name=\"search\"> <input type=\"submit\"\n");
      out.write("\t\t\t\t\tvalue=\"Search\">\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<!-- guarantee -->\n");
      out.write("\n");
      out.write("\t<section id=\"history\" class=\"section\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"text-content\">\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"headline\">Company History</h2>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tIn 2006, H+ Sport founder <a href=\"#employees-henrytwill\">Henry\n");
      out.write("\t\t\t\t\t\t\t\t\tTwill</a> set out to create supplements and nutritional products\n");
      out.write("\t\t\t\t\t\t\t\tmade from the <em>purest ingredients</em> and backed by\n");
      out.write("\t\t\t\t\t\t\t\tscientific and <em>performance data</em> â to provide a strong\n");
      out.write("\t\t\t\t\t\t\t\tbasis of <em>trust and accountability</em>.\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tHis quest began while training for his <em>first 5K\n");
      out.write("\t\t\t\t\t\t\t\t\tmarathon</em>, after recovering from a <em>lengthy injury</em> that\n");
      out.write("\t\t\t\t\t\t\t\tleft him with residual aches, pains, and decreased athletic\n");
      out.write("\t\t\t\t\t\t\t\tperformance. He yearned for <em>simple and natural\n");
      out.write("\t\t\t\t\t\t\t\t\tingredients</em>, in their purest form, instead of labels with <em>lengthy\n");
      out.write("\t\t\t\t\t\t\t\t\tchemical names</em> and disclaimers. When no products lived up to\n");
      out.write("\t\t\t\t\t\t\t\this strict requirements, Henry set his sights on <em>creating\n");
      out.write("\t\t\t\t\t\t\t\t\tproducts</em> that catered to his own vision.\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tToday that vision has become H+ Sportâ¦offering a variety of <a\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"#products\">supplements, energy bars and rehydration\n");
      out.write("\t\t\t\t\t\t\t\t\tsolutions</a>. At the foundation of H+ Sports are products backed\n");
      out.write("\t\t\t\t\t\t\t\tby scientific and performance data.\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- container text -->\n");
      out.write("\t</section>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<section id=\"people\" class=\"section\">\n");
      out.write("  <header class=\"imageheader\"></header>\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <h2 class=\"headline\">People</h2>\n");
      out.write("    <div class=\"people-cards\">\n");
      out.write("      <div class=\"person-card\">\n");
      out.write("        <img src=\"images/employees/HenryTwill.jpg\" alt=\"HenryTwill Photo\">\n");
      out.write("        <div class=\"card-info\">\n");
      out.write("          <h3 class=\"card-name\">Henry Twill, Jr</h3>\n");
      out.write("          <h4 class=\"card-title\">CEO</h4>\n");
      out.write("        </div>\n");
      out.write("        <p class=\"card-text\">Henry Twill Jr. is the <em>founder</em> and CEO of H+ Sports. Previously he was an <em>athletic trainer</em> working with several top athletes, making sure that they had the direction and proper coaching to keep them at the <em>top of their game</em>. Henryâs passion for finding natural alternatives led him to developing H+ Sport Multivitamins. The supplements <em>became a success</em> with his clients and led to the creation of H+ Sports.</p>\n");
      out.write("      </div><!-- person-card -->\n");
      out.write("\n");
      out.write("      <div class=\"person-card\">\n");
      out.write("        <img src=\"images/employees/JessicaNewton.jpg\" alt=\"JessicaNewton Photo\">\n");
      out.write("        <div class=\"card-info\">\n");
      out.write("          <h3 class=\"card-name\">Jessica Newton-Smith, MBA</h3>\n");
      out.write("          <h4 class=\"card-title\">CFO</h4>\n");
      out.write("        </div>\n");
      out.write("        <p class=\"card-text\">Jessica Newton-Smith joined us in 2012 and brings more than <em>10 years</em> of financial management experience to H+ Sports, spanning a variety of companies and industries ranging from <em> Fortune 500 agencies</em> to start-ups. She has extensive experience working in <em>emerging markets</em> and in the consumer and retail sectors.</p>\n");
      out.write("      </div><!-- person-card -->\n");
      out.write("\n");
      out.write("      <div class=\"person-card\">\n");
      out.write("        <img src=\"images/employees/PhiTang.jpg\" alt=\"PhiTang Photo\">\n");
      out.write("        <div class=\"card-info\">\n");
      out.write("          <h3 class=\"card-name\">Phi Tang, MBA</h3>\n");
      out.write("          <h4 class=\"card-title\">Director of Product Development</h4>\n");
      out.write("        </div>\n");
      out.write("        <p class=\"card-text\">Phi Tang joined H+ Sports in <em>2007</em> as Manager of Marketing Research. He was promoted to Director of Product Development in 2011. He has made <em>major contributions</em> to the discovery, development, and implementation of the H+ Sport product lines. Before joining the company he worked as a <em>scientific expert</em> and brings vast knowledge of ingredients and <em>new technologies</em>.</p>\n");
      out.write("      </div><!-- person-card -->\n");
      out.write("\n");
      out.write("      <div class=\"person-card\">\n");
      out.write("        <img src=\"images/employees/MariaSontas.jpg\" alt=\"MariaSontas Photo\">\n");
      out.write("        <div class=\"card-info\">\n");
      out.write("          <h3 class=\"card-name\">Maria Sontas</h3>\n");
      out.write("          <h4 class=\"card-title\">Director of Marketing</h4>\n");
      out.write("        </div>\n");
      out.write("        <p class=\"card-text\">Maria Sontas has been with H+ Sport since 2010. She oversees the companyâs <em>marketing strategy</em> â ensuring advertising campaigns, social media initiatives, and events are planned to <em>position the company</em> strongly in a competitive marketplace. Maria is a <em>competing triathlete</em> and her passion for our products shows in her unique ability to drive awareness and <em>increase our presence</em> around the world.</p>\n");
      out.write("      </div><!-- person-card -->\n");
      out.write("\n");
      out.write("      <div class=\"person-card\">\n");
      out.write("        <img src=\"images/employees/AngelaHaston.jpg\" alt=\"AngelaHaston Photo\">\n");
      out.write("        <div class=\"card-info\">\n");
      out.write("          <h3 class=\"card-name\">Angela Hashton</h3>\n");
      out.write("          <h4 class=\"card-title\">Director of Sales</h4>\n");
      out.write("        </div>\n");
      out.write("        <p class=\"card-text\">Angela Hashton joined the company in 2009, to <em>initiate new relationships</em> for our growing line of H+ Sports active apparel. After being with the company for a year, she was promoted to Director of Sales. Angela is the drive behind the H+ Sport <em>ACTIVE product line</em> and has an uncanny ability to formulate strategies that have helped build our unified sales force. <em>Educating people</em> about health and nutrition is something that Angela holds dear.</p>\n");
      out.write("      </div><!-- person-card -->\n");
      out.write("\n");
      out.write("      <div class=\"person-card\">\n");
      out.write("        <img src=\"images/employees/MichaelLewiston.jpg\" alt=\"MichaelLewiston Photo\">\n");
      out.write("        <div class=\"card-info\">\n");
      out.write("          <h3 class=\"card-name\">Michael Lewiston</h3>\n");
      out.write("          <h4 class=\"card-title\">MFA, Creative Director</h4>\n");
      out.write("        </div>\n");
      out.write("        <p class=\"card-text\">Michael Lewiston is a multi-faceted <em>creative person</em> who began his career as a designer for a small business firm, while also working as an independent <em>painter and sculptor</em>. In 2007, Henry Twill was impressed by Michaelâs creative work in a national ad campaign for a high profile sports apparel company. Henry approached Michael, and asked him to <em>manage creative direction</em> for the H+ Sport ACTIVE apparel line.</p>\n");
      out.write("      </div><!-- person-card -->\n");
      out.write("  </div><!-- container -->\n");
      out.write("</section><!-- people -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<footer class=\"footer\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<nav class=\"nav\" role=\"navigation\">\n");
      out.write("\t\t\t\t<div class=\"container nav-elements\">\n");
      out.write("\t\t\t\t\t<div class=\"branding\">\n");
      out.write("\t\t\t\t\t\t<a href=\"#home\"><img src=\"images/hpluslogo.svg\"\n");
      out.write("\t\t\t\t\t\t\talt=\"Logo - H Plus Sports\"></a>\n");
      out.write("\t\t\t\t\t\t<p class=\"address\">\n");
      out.write("\t\t\t\t\t\t\t100 Main Street<br> Seattle, WA 98144\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t\t<p class=\"legal\">H+ Sport is a fictitious brand created by\n");
      out.write("\t\t\t\tlynda.com solely for the purpose of training. All products and\n");
      out.write("\t\t\t\tpeople associated with H+ Sport are also fictitious. Any resemblance\n");
      out.write("\t\t\t\tto real brands, products, or people is purely coincidental.\n");
      out.write("\t\t\t\tInformation provided about the product is also fictitious and should\n");
      out.write("\t\t\t\tnot be construed to be representative of actual products on the\n");
      out.write("\t\t\t\tmarket in a similar product category.</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- container -->\n");
      out.write("\t</footer>\n");
      out.write("\t<!-- footer -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
